[tool.poetry]
name = "histopathology"
version = "0.0.1"
description = ""
authors = ["Petr Smirnov"]
readme = "README.md"
packages = [{include = "src", from = "."}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
